# -*- coding: utf-8 -*-
"""Apriori algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_svhhqsdZnHWuIXsyfOLE7HnXfVgjv3
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/transa.csv', header = None)
df

df.isnull().sum()

df.values.tolist()

T = []
for i in range(len(df)):
  T.append([str(df.values[i,j]) for j in range (0,10)])

T = []
for i in range(len(df)):
  T.append([str(df.values[i,j]) for j in range (0,10) if str(df.values[i, j])!= 'nan'])

T

!pip install apyori
#from apyori import apriori

from apyori import apriori

rules = apriori(T, min_support = 0.002, min_confidence = 0.05, min_lift = 2, min_length = 2) 
x = list(rules)
x[:10]

for item in x:  
    pair = item[0]   
    items = [x for x in pair]  
    print("Rule: " + items[0] + " -> " + items[1])  
  
    print("Support: " + str(item[1]))  
    print("Confidence: " + str(item[2][0][2]))  
    print("Lift: " + str(item[2][0][3]))  
    print("=====================================")